import os
from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT_NAME = (
    os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")
    or os.getenv("AZURE_OPENAI_DEPLOYMENT")
)
SALESFORCE_LOGIN_URL = os.getenv("SALESFORCE_LOGIN_URL", "https://login.salesforce.com")
SALESFORCE_CLIENT_ID = os.getenv("SALESFORCE_CLIENT_ID")
SALESFORCE_CLIENT_SECRET = os.getenv("SALESFORCE_CLIENT_SECRET")
SALESFORCE_API_VERSION = os.getenv("SALESFORCE_API_VERSION", "v61.0")
SALESFORCE_RETURN_ORDER_OBJECT = os.getenv("SALESFORCE_RETURN_ORDER_OBJECT", "ReturnOrder")
SALESFORCE_RETURN_ORDER_ACCOUNT_FIELD = os.getenv("SALESFORCE_RETURN_ORDER_ACCOUNT_FIELD", "AccountId")
SALESFORCE_RETURN_ORDER_ORDER_FIELD = os.getenv("SALESFORCE_RETURN_ORDER_ORDER_FIELD", "OrderId")

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
SENDGRID_FROM_EMAIL = os.getenv("SENDGRID_FROM_EMAIL")
SENDGRID_TIMEOUT = float(os.getenv("SENDGRID_TIMEOUT", "30"))

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_FROM_NUMBER = os.getenv("TWILIO_FROM_NUMBER")
TWILIO_TIMEOUT = float(os.getenv("TWILIO_TIMEOUT", "30"))
